config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

   root 'sessions#new'

     resources :posts
     resources :users

     get 'signup' => 'users#new'
     post 'signup' => 'usesr#create'

     get 'login' => 'sessions#new'
     post 'login' => 'sessions#create'
     delete 'logout' => 'sessions#destroy'

     put 'posts/:id/vote_up' => 'posts#vote_up', :as => 'vote_up'
     put 'posts/:id/vote_down' => 'posts#vote_down', :as => 'vote_down'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  before_save :default_values

  def default_values
    self.score ||= 0
    if self.lifespan = nil
      new_record?
    end
    self.lifespan ||= 3600
    self.destruct_at = self.lifespan.seconds.from_now if new_record?
  end

  def reset_score
    self.score = 0
    self.save
  end

  def is_not_destructed?
    Time.now < self.destruct_at
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  
  before_save :default_values

  has_secure_password

  def default_values
    self.score ||= 0
    self.post_count ||= 0
  end

  def update_post_count
    count = 0
    self.posts.each do |post|
      count += 1
    end
    self.post_count = count
    self.save
  end

  def reset_score
    self.score = 0
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  #before_filter :require_login

  private
  
  #def require_login
  #  if logged_in? == false
  #    redirect_to signup_path
  #  end
  #end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    user = current_user
    @post = user.posts.new
    @title = "Posts"
    users = User.all
    posts = []
    users.each do |user|
      post_query = user.posts.where('destruct_at > ?', Time.now)
      if !post_query.empty?
        posts << post_query.last
      end
    end
    @posts = posts.sort_by {|post| post[:created_at] }.reverse
  end
  
#  def new
#    @title = "Write new post"
#    user = current_user
#    @post = user.posts.new
#  end
  
  def create
    user = current_user
    last_post = user.posts.last
    if last_post.is_not_destructed?
      last_post.lifespan = (last_post.destruct_at - (last_post.destruct_at - Time.now)).to_i
      last_post.save
    end
    @post =user.posts.new(post_params)
    if @post.save
      flash[:success] = "Post submitted"
      user.post_count = user.post_count + 1
      redirect_to posts_path
    else
      render :new
    end

  end
  
  def show

  end
  
  def edit
 
  end
  
  def update

  end
  
  def delete

  end
  
  def destroy

  end

  def post_params
    params.require(:post).permit(:title, :content, :score, :lifespan)
  end

  def vote_up
    @post = Post.find_by_id(params[:id])
    @user = @post.user
    @user.score += 1
    @post.score += 1
    if @user.save && @post.save
      flash[:success] = "Score UPdated"
      redirect_to posts_path
    else
      flash[:danger] = "Something went wrong"
      redirect_to posts_path
    end
  end
  def vote_down
    @post = Post.find_by_id(params[:id])
    @user = @post.user
    @post.score += -1
    @user.score += -1
    if @user.save && @post.save
      flash[:success] = "Score DOWNgraded"
      redirect_to posts_path
    else
      flash[:danger] = "Something went wrong"
      redirect_to posts_path
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to posts_path
    end
  end
  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      #Log In
      log_in user
      redirect_to posts_path
    else
      #Fail
      flash.now[:danger] = "Incorrect username/password combination"
      render 'new'
    end
  end
  def destroy
    session[:user_id] = nil
    flash[:success] = "User successfully logged out!" 
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @title = "User List"
    @users = User.all
  end
  def new
    if logged_in?
      redirect_to posts_path
    end
    @title = "Sign up!"
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User successfully saved!"
      log_in(@user)
      redirect_to posts_path
    else
      @title = "Sign up!"
      render :new
    end
    
  end

  def show
    @user = User.find(params[:id])
    @title = @user.username
  end

  def user_params
    params.require(:user).permit(:username, :password, :score, :post_count)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def get_countdown(post)
    countdown = post.destruct_at - Time.now
    hours_and_seconds = countdown.divmod(3600)
    minutes_and_seconds = hours_and_seconds[1].divmod(60)

    @hours = hours_and_seconds[0].to_s.rjust(2, '0')
    @minutes = minutes_and_seconds[0].to_s.rjust(2, '0')
    @seconds = minutes_and_seconds[1].to_i.to_s.rjust(2, '0')

    time_to_destruct = "#{@hours}:#{@minutes}:#{@seconds}"
    return time_to_destruct
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <table>
    <% flash.each do |key, value| %>
    <tr>
      <td>
        <%= key %>
      </td>
      <td>
        <%= value %>
      </td>
    </tr>
    <% end %>
  </table>
  <% if logged_in? %>
    <p>Welcome <%= current_user.username %>|<%= link_to "Log Out", logout_path, method: :delete %></p>
  <% else %>
    <%= link_to "Login", login_path %>
  <% end %>
  <h1><%= @title %></h1>
  <%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :content %><br/>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>
<% column = 0 %>
<% @posts.each do |post| %>
  <% column += 1 %>
  <% if column == 1 %>
    <div>
  <% end %>
  <div class="post">
    <h2><%= post.title %></h2>
    <h4>
      <%= link_to post.user.username, user_path(post.user.id) %> | 
      <%= link_to "-", vote_down_path(post.id), method: :put if post.user != current_user %>
      (<%= post.user.score %>)
      <%= link_to "+", vote_up_path(post.id), method: :put if post.user != current_user %>
    </h4>
    <h5>
      <span class="countdown"><%= get_countdown(post) %></span> remaining
    </h5>

    <p><%= post.content %></p>
  </div>
  <% if column == 5 %>
    </div>
  <% end %>
  <% column = 0 if column == 5  %>
<% end %>
<% if column != 0 %>
  </div>
<% end %>

app/views/users/index.html.erb
<table>
  <% @users.each do |user| %>
    <tr>
      <td>
        <%= user.username %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.label :username %></br>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :password %></br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %></br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<div>
  <strong>score:</strong> <%= @user.score %><br/>
  <strong># of posts:</strong> <%= @user.post_count %> 
</div>